/**
 * Acceptance pair for ADR-EC-038 / BEH-EC-030 / REQ-EC-030: `rerun-failed-only.feature` run through
 * the real `describeFeature`, with `rerunFailedOnly: true` and a HAND-COMPUTED, committed manifest
 * (`rerun-failed-only.manifest.json`) naming only the FIRST Scenario's own rerun key. Proves the READ
 * side of ADR-EC-038 end to end: the second Scenario's steps structurally never run at all —
 * registration-time exclusion, not "ran and got skipped" — because an observer reads the SAME shared
 * Ref-backed log both Scenarios would append to and finds only the first Scenario's own marker.
 *
 * The manifest's one key was computed BY HAND, off `RerunKey.ts`'s own documented format
 * (`${uri}::${ruleName ?? ""}::${title}`) — not generated by the write-side script, which is proven
 * separately, for real, by `scripts/verify-rerun-failed-only.sh` (a genuine two-`vitest run` cycle,
 * which a single acceptance Scenario cannot express by construction — a single run cannot prove what
 * a SECOND, separately-invoked run does differently).
 *
 * `uri` here is deliberately the LITERAL string this file hands to `loadFeature` below — a path
 * relative to the REPOSITORY ROOT, not `fileURLToPath(new URL(..., import.meta.url))` the way this
 * directory's other acceptance pairs use. A hand-computed, committed manifest has to name a value
 * that is the SAME on every machine that checks this repository out; an absolute filesystem path
 * (which is what `fileURLToPath` would produce) is not that. `loadFeature`'s underlying
 * `NodeFileSystem.readFileString` resolves a relative path against `process.cwd()`, which is the
 * repository root for every invocation this pair is proven under (`pnpm test`, the root
 * `pnpm vitest run --root packages/vitest ...`, and CI) — a deliberate, disclosed deviation from the
 * sibling pairs' own convention, made for this one file's own reason.
 *
 * Carries: ADR-EC-038, BEH-EC-030, REQ-EC-030.
 */
import { assert, describe, it } from "@effect/vitest"
import * as Context from "effect/Context"
import * as Effect from "effect/Effect"
import * as Layer from "effect/Layer"
import * as Ref from "effect/Ref"
import { fileURLToPath } from "node:url"
import { describeFeature } from "../../src/describeFeature.ts"
import { loadFeature } from "../../src/loadFeature.ts"

// Repo-root-relative — see the header comment above for why this differs from every sibling pair.
const featureUri = "packages/vitest/test/acceptance/rerun-failed-only.feature"
const feature = await loadFeature(featureUri)

// The committed, hand-computed manifest naming only the FIRST Scenario's rerun key. Resolved via
// `fileURLToPath` here (not repo-root-relative): `rerunManifestPath` is read by `RerunManifest.ts`
// with plain `node:fs`, which has no notion of "relative to this test file" the way `loadFeature`'s
// uri argument does — an absolute path is the correct, unambiguous choice for THIS argument.
const manifestPath = fileURLToPath(new URL("./rerun-failed-only.manifest.json", import.meta.url))

// Built once, at module scope — a `const`, never a `let`/`var` (INV-EC-006) — and handed to BOTH the
// shared Layer below (so a step reaches it via `yield* RerunLog`, a Layer-provided Ref) AND the
// observer at the bottom of this file, directly, so it can read the SAME instance without asking the
// framework to build the shared tier a second time (which a `Layer.effect` acquisition would do,
// handing the observer a fresh, empty Ref instead of the one Scenario steps actually wrote to).
const sharedLogRef = Effect.runSync(Ref.make<ReadonlyArray<string>>([]))

// SHARED tier (INV-EC-006): the log must survive across both Scenarios' own `it.effect` nodes, so it
// cannot live in the `perScenario` tier, which is rebuilt fresh per Scenario by design.
class RerunLog extends Context.Service<RerunLog, {
  readonly entries: Ref.Ref<ReadonlyArray<string>>
}>()("RerunFailedOnlyAcceptanceLog") {
  static readonly layer = Layer.succeed(this, RerunLog.of({ entries: sharedLogRef }))
}

// A name-less, UNSHUFFLED block — the identical shape `emission.test.ts`'s own `orderedBlock` and
// `metrics.steps.test.ts`'s own copy of it use — so the `describeFeature` call and the observer
// block below that reads what it recorded stay adjacent under `pnpm test:shuffle` (AGENTS.md §5: "an
// observer describe that reads what an earlier suite recorded sits in the SAME unshuffled block as
// that suite, never as a later sibling").
const unshuffledSuite: typeof describe = describe
const orderedBlock = (block: () => void): void => {
  unshuffledSuite("", { shuffle: false }, block)
}

orderedBlock(() => {
  // THE CALL UNDER TEST: `rerunFailedOnly: true` against the fixed manifest above, which names only
  // the first Scenario. The second Scenario is excluded at REGISTRATION time — its steps below are
  // never even reachable, since `describeFeature` never emits an `it.effect` node for it at all.
  describeFeature(
    feature,
    { shared: RerunLog.layer, perScenario: Layer.empty },
    ({ Given, Then }) => {
      Given("the rerun log records {string}", function*(title: string) {
        const log = yield* RerunLog
        yield* Ref.update(log.entries, (entries) => [...entries, title])
      })
      Then("the rerun log contains {string}", function*(title: string) {
        const log = yield* RerunLog
        const entries = yield* Ref.get(log.entries)
        assert.ok(entries.includes(title))
      })
    },
    { rerunFailedOnly: true, rerunManifestPath: manifestPath }
  )

  describe("rerunFailedOnly excludes a Scenario at registration, not merely at run time (ADR-EC-038, BEH-EC-030)", () => {
    it.effect(
      "the log contains ONLY the manifest-named Scenario's marker — the sibling Scenario's steps never ran at all",
      () =>
        Effect.gen(function*() {
          const entries = yield* Ref.get(sharedLogRef)
          assert.deepStrictEqual(entries, ["A previously failing scenario reruns"])
        })
    )
  })
})
