#!/usr/bin/env bash
#
# Asserts that every worked-example ```typescript fence under spec/ still compiles against the
# real, current package API — the failure mode this exists for is a spec doc that keeps reading
# as true after the API it shows has moved. A fence may opt out with a `// doc-examples:skip —
# <reason>` first line (for a fence that is deliberately illustrative shorthand, not a standalone
# program); every skip is reported by name, never silent. Positive control: a deliberately broken
# fixture, generated fresh every run, must fail the same compile step before a clean run on the
# real fences is trusted.
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

GEN_DIR="packages/vitest/test/doc-examples/generated"
BASE_CONFIG="packages/vitest/test/doc-examples/tsconfig.json"
TSC="node node_modules/typescript/bin/tsc"

fail() {
  echo ""
  echo "✗ doc-examples: NOT ENFORCED"
  echo ""
  echo "  $1"
  echo ""
  exit 1
}

[[ -f "$BASE_CONFIG" ]] || fail "missing $BASE_CONFIG — the shared compiler options are absent, so nothing was verified."

rm -rf "$GEN_DIR"
mkdir -p "$GEN_DIR"

# ---------------------------------------------------------------------------
# Extraction: every ```typescript fence under spec/ becomes one file in $GEN_DIR, or is recorded
# as skipped. Node does the extraction (line-oriented state machine); bash drives the two tsc runs.
# ---------------------------------------------------------------------------
EXTRACT_OUTPUT="$(node - "$GEN_DIR" <<'NODE'
const fs = require("node:fs")
const path = require("node:path")
const genDir = process.argv[2]

const walk = (dir) => {
  const out = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) out.push(...walk(full))
    else if (entry.name.endsWith(".md")) out.push(full)
  }
  return out
}

const files = walk("spec").sort()
const generated = []
const skipped = []

for (const file of files) {
  const lines = fs.readFileSync(file, "utf8").split("\n")
  let i = 0
  while (i < lines.length) {
    if (lines[i].trim() === "```typescript") {
      const startLine = i + 2 // 1-indexed, the line after the fence marker
      const body = []
      i++
      while (i < lines.length && lines[i].trim() !== "```") {
        body.push(lines[i])
        i++
      }
      const skipMatch = body[0] && body[0].match(/^\/\/\s*doc-examples:skip\s*—\s*(.+)$/)
      if (skipMatch) {
        skipped.push({ file, line: startLine, reason: skipMatch[1] })
      } else {
        const base = file.replace(/^spec\//, "").replace(/\//g, "-").replace(/\.md$/, "")
        const name = `${base}-L${startLine}.ts`
        const header = `// generated by scripts/verify-doc-examples.sh from ${file}:${startLine} — do not edit directly\n`
        fs.writeFileSync(path.join(genDir, name), header + body.join("\n") + "\n")
        generated.push(name)
      }
    }
    i++
  }
}

if (generated.length === 0) {
  console.error("POSITIVE_CONTROL_FAIL: no ```typescript fence was found under spec/ — the extraction scan is broken")
  process.exit(1)
}

const controlName = "__positive_control__.ts"
fs.writeFileSync(
  path.join(genDir, controlName),
  "// planted by scripts/verify-doc-examples.sh — must fail to compile, proving the gate is live\nconst _control: number = \"not a number\"\n"
)

fs.writeFileSync(
  path.join(genDir, "tsconfig.control.json"),
  JSON.stringify({ extends: "../tsconfig.json", include: [], files: [`./${controlName}`] }, null, 2) + "\n"
)
fs.writeFileSync(
  path.join(genDir, "tsconfig.generated.json"),
  JSON.stringify({ extends: "../tsconfig.json", include: [], files: generated.map((n) => `./${n}`) }, null, 2) + "\n"
)

console.log(`GENERATED ${generated.length}`)
for (const name of generated) console.log(`  ${name}`)
console.log(`SKIPPED ${skipped.length}`)
for (const s of skipped) console.log(`  ${s.file}:${s.line} — ${s.reason}`)
NODE
)" || fail "fence extraction failed — see output above."

GENERATED_COUNT="$(echo "$EXTRACT_OUTPUT" | grep -oE '^GENERATED [0-9]+' | grep -oE '[0-9]+')"
SKIPPED_COUNT="$(echo "$EXTRACT_OUTPUT" | grep -oE '^SKIPPED [0-9]+' | grep -oE '[0-9]+')"
echo "$EXTRACT_OUTPUT"

# ---------------------------------------------------------------------------
# Positive control: the planted type error must fail, with the diagnostic naming a real type
# mismatch — not TS6059/TS2688/TS2584 config-resolution noise, which would make this pass for
# the wrong reason.
# ---------------------------------------------------------------------------
CONTROL_OUTPUT="$($TSC -p "$GEN_DIR/tsconfig.control.json" 2>&1)" && CONTROL_EXIT=0 || CONTROL_EXIT=$?
if [[ "$CONTROL_EXIT" -eq 0 ]]; then
  fail "positive control did not fail to compile — the compile step is not actually checking types, so a clean run on the real fences below would be vacuous."
fi
if ! echo "$CONTROL_OUTPUT" | grep -q "error TS2322"; then
  fail "positive control failed, but not with the expected TS2322 (type mismatch) — got:
$CONTROL_OUTPUT"
fi
echo "✓ positive control: a planted type error is caught (TS2322)"

# ---------------------------------------------------------------------------
# The real fences must compile clean.
# ---------------------------------------------------------------------------
REAL_OUTPUT="$($TSC -p "$GEN_DIR/tsconfig.generated.json" 2>&1)" && REAL_EXIT=0 || REAL_EXIT=$?
if [[ "$REAL_EXIT" -ne 0 ]]; then
  fail "one or more spec/ worked examples no longer compile against the real API — every diagnostic
  below names the generated file's header comment, which names the source spec/*.md:line to fix:

$REAL_OUTPUT"
fi
echo "✓ $GENERATED_COUNT worked-example fence(s) under spec/ compile against the real API ($SKIPPED_COUNT explicitly skipped, listed above)"

echo ""
echo "doc-examples: ENFORCED"
